# Generated by Django 2.1 on 2018-11-21 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='user',
            field=models.ForeignKey(default=1, limit_choices_to={'is_teacher': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='classform',
            name='class_form_name',
            field=models.CharField(choices=[('LAB', 'Labolatory'), ('PRO', 'Project'), ('CLA', 'Class'), ('LEC', 'Lecture')], default='LAB', max_length=10),
        ),
    ]
