# Generated by Django 2.1 on 2018-11-21 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20181121_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classform',
            name='class_form_name',
            field=models.CharField(choices=[('LAB', 'Labolatory'), ('PRO', 'Project'), ('CLA', 'Class'), ('LEC', 'Lecture')], default='LAB', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
