# Generated by Django 2.1 on 2018-11-21 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_auto_20181121_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='class_form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.ClassForm', to_field='class_form_name'),
        ),
        migrations.AlterField(
            model_name='class',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.Subject', to_field='subject_name'),
        ),
    ]
