# Generated by Django 2.1 on 2018-11-21 19:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_auto_20181121_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='class_form',
            field=models.CharField(choices=[('LAB', 'Laboratory'), ('PRO', 'Project'), ('CLA', 'Class'), ('LEC', 'Lecture')], default='LAB', max_length=10),
        ),
        migrations.AlterField(
            model_name='class',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reports.Subject'),
        ),
        migrations.AlterField(
            model_name='class',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ClassForm',
        ),
    ]
