# Generated by Django 2.1 on 2018-11-22 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_auto_20181122_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportsent',
            name='class_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reports.Class'),
        ),
        migrations.AlterField(
            model_name='class',
            name='class_name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
