# Generated by Django 2.1 on 2018-12-02 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_auto_20181122_1339'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='class',
            name='class_name',
        ),
        migrations.AlterField(
            model_name='reportsent',
            name='report_topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.ReportTopic'),
        ),
        migrations.AddField(
            model_name='reporttopic',
            name='class_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.Class'),
        ),
    ]
