# Generated by Django 2.1 on 2018-12-04 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_auto_20181202_1333'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(choices=[('EA-DI(01)', 'EA-DI(01)'), ('EA-DI(02)', 'EA-DI(02)'), ('EA-DI(03)', 'EA-DI(03)'), ('EA-DI(04)', 'EA-DI(04)'), ('EA-DI(05)', 'EA-DI(05)'), ('EA-DI(06)', 'EA-DI(06)'), ('EA-DI(07)', 'EA-DI(07)'), ('EF-DI(01)', 'EF-DI(01)'), ('EF-DI(02)', 'EF-DI(02)'), ('EF-DI(03)', 'EF-DI(03)'), ('EF-DI(04)', 'EF-DI(04)'), ('EF-DI(05)', 'EF-DI(05)'), ('EF-DI(06)', 'EF-DI(06)'), ('EF-DI(07)', 'EF-DI(07)')], default='EA-DI(01)', max_length=30, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='reportsent',
            name='class_id',
        ),
        migrations.AddField(
            model_name='class',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reports.Course'),
        ),
    ]
