# Generated by Django 2.1 on 2018-12-04 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_auto_20181204_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='course',
            field=models.ForeignKey(choices=[('EA-DI(01)', 'EA-DI(01)'), ('EA-DI(02)', 'EA-DI(02)'), ('EA-DI(03)', 'EA-DI(03)'), ('EA-DI(04)', 'EA-DI(04)'), ('EA-DI(05)', 'EA-DI(05)'), ('EA-DI(06)', 'EA-DI(06)'), ('EA-DI(07)', 'EA-DI(07)'), ('EF-DI(01)', 'EF-DI(01)'), ('EF-DI(02)', 'EF-DI(02)'), ('EF-DI(03)', 'EF-DI(03)'), ('EF-DI(04)', 'EF-DI(04)'), ('EF-DI(05)', 'EF-DI(05)'), ('EF-DI(06)', 'EF-DI(06)'), ('EF-DI(07)', 'EF-DI(07)')], default='EA-DI(01)', on_delete=django.db.models.deletion.CASCADE, to='reports.Course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
