# Generated by Django 2.1 on 2018-12-04 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0011_auto_20181204_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportsent',
            name='comment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reportsent',
            name='grade',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
