# Generated by Django 2.1 on 2018-12-04 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0012_auto_20181204_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportsent',
            name='file',
            field=models.FileField(max_length=200, upload_to='uploads/%Y,%m,%d'),
        ),
    ]
