# Generated by Django 2.1 on 2018-12-20 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0014_auto_20181204_2140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newstudent',
            name='report_sent',
        ),
        migrations.RemoveField(
            model_name='newstudent',
            name='user',
        ),
        migrations.RemoveField(
            model_name='studentclass',
            name='class_id',
        ),
        migrations.RemoveField(
            model_name='studentclass',
            name='user',
        ),
        migrations.DeleteModel(
            name='NewStudent',
        ),
        migrations.DeleteModel(
            name='StudentClass',
        ),
    ]
